### PR TITLE
Pass lint, vet and consolidate.

### PR DESCRIPTION
**Pull request by buddhamagnet**
Love the fact there is a CMS in Go!

I have taken the time to go through the codebase and endure it passes `golint`, `go vet`, all fucntions and methods are commented correctly for `godoc` and made some changes to the way roles are queried to make it less repetitive. Hope this helps, especially if you'd like to attract contributors. I have the following settings in GoSublime if you use that:

``` json
"on_save": [{
      "cmd": "gs9o_open", "args": {
        "run": ["sh",
          "errcheck && godep go build . errors && godep go test -i && godep go test && go vet && golint ."],
    "focus_view": false
    }}],
    "autocomplete_closures": true,
    "complete_builtins": true,
```

Hope this helps! All tests are passing but I did notice the following which was already issuing a warning:

``` txt
src/lib/mail/mail.go:46: cannot use renderContext literal (type *renderContext) as type view.RenderContext in argument to view.New:
    *renderContext does not implement view.RenderContext (missing Writer method)
src/lib/mail/mail.go:53: view.RenderString undefined (type *view.Renderer has no field or method RenderString)
```

### CODE REVIEW

**Comment by kennygrant** [comment]
Thanks, I'll have a look and see if I can merge it. In theory if just linter changes it should be fine, but I'll need to look at the roles stuff you mentioned.  

Ideally before a pull request just put up an issue with your plans, so that we can discuss it first. Also try to separate out changes into small discrete ones (for example roles should be separate).

**Comment by buddhamagnet** [comment]
No problems @kennygrant will bear that in mind in future.

**Comment by buddhamagnet** [comment]
Looking good @kennygrant or want me to close it?

**Comment by kennygrant** [comment]
I'm still looking at it, there are a few changes that still need to be made if all the refs to Id are to be renamed like this (for example refs in templates). Leave it with me and I'll get it merged.

**Comment by kennygrant** [comment]
Thanks for your contribution. 

I've taken in the suggestion to rename Id -> ID and Url to URL now, and I think it now passes the linter everywhere so all those code comments are done, but unfortunately I did this as a large refactor so I'm going to close this now. For future pull requests please try to tie them to an issue first, and keep them smaller so that they're easier to merge.

**Pull request closed without merging**
